name: GitHub Versioning
on:
  push:
    branches: [main]
concurrency: versioning-${{ github.ref }}
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/continuous-integration.yml
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      trigger-publish: ${{ steps.changesets.outputs.published == 'true' }}
    strategy:
      matrix:
        node-version: [17.8.0]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # ratchet:actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - uses: changesets/action@5f3b898718761af42fe162af3258e4145d07be24 # ratchet:changesets/action@v1
        id: changesets
        with:
          createGithubReleases: false
          publish: "echo New tag: @workspace/root@package" # Trigger publish
          version: yarn change:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: well-known
  start-deploy:
    name: Start Deployment
    needs: [ci, version]
    if: needs.version.outputs.trigger-publish == 'true'
    uses: ./.github/workflows/continuous-deployment.yml
    secrets: inherit
